{{- if .Values.connector.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector.fullname" . }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.connector.service.type }}
  ports:
    - port: {{ .Values.connector.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "connector.selectorLabels" . | nindent 4 }}
{{- end }}