apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webrtc-observer.fullname" . }}-secret
data:
  databaseUsername: {{ .Values.secret.databaseUsername | b64enc | quote }}
  databasePassword: {{ .Values.secret.databasePassword | b64enc | quote }}
  jdbcURI: {{ with .Values.secret.jdbcURI -}}
  {{- list "jdbc:" .databaseType "://" .serverAddress ":" .port "/" .databaseName | join ""  | b64enc |  quote }}
  {{- end }}