{{- if .Values.connector.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}-config
data:
{{- with .Values.connector.config }}
  connector.yaml: |
{{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}