{{- if .Values.connector.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "connector.fullname" . }}-config
data:
{{- with .Values.connector.micronaut.config }}
  micronaut-config.yaml: |
{{- toYaml . | nindent 4 }}
{{- end }}
{{ range $key, $value := .Values.connector.pipelines }}
  {{ $key }}: |
  {{- toYaml $value | nindent 4 }}
{{ end }}
{{- end }}