{{- if .Values.kafka.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kafka.service.type }}
#  clusterIP: None
  ports:
    - port: {{ .Values.kafka.service.port }}
      protocol: TCP
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
{{- end }}