{{- if .Values.kafka.pvc.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "kafka.pvcName" . }}
  labels:
  {{- include "kafka.labels" . | nindent 4 }}
  {{- with .Values.kafka.pvc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.kafka.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.kafka.pvc.size | quote }}
{{- end }}