{{- if .Values.observer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "observer.fullname" . }}
  labels:
    {{- include "observer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.observer.service.type }}
  ports:
    - port: {{ .Values.observer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "observer.selectorLabels" . | nindent 4 }}
{{- end }}