{{- if .Values.observer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webrtc-observer.serviceAccountName" . }}
  labels:
    {{- include "webrtc-observer.labels" . | nindent 4 }}
  {{- with .Values.observer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
